.\" cloudnbd 0.1 man page
.TH cloudnbd 1 "29 Oct 2011" "Mansour"
.SH NAME
cloudnbd \- NBD server with cloud storage as backend
.SH SYNOPSIS
.na
\fBcloudnbd\fP [\fB-h\fP] [\fB-v\fP]

\fBcloudnbd\fP [\fIoption\fP] \fIcommand\fP [\fB\-h\fP] \&.\&.\&.

\fBcloudnbd\fP [\fIoption\fP] \fBclose\fP \
\fIbackend\fP \
\fIvolume\fP

\fBcloudnbd\fP [\fIoption\fP] \fBcloseall\fP

\fBcloudnbd\fP [\fIoption\fP] \fBdelete\fP \
[\fIauth_option\fP] \
[\fB\-\-yes\fP] \
[\fB\-t\fP \fIcount\fP] \
\fIbackend\fP \
\fIvolume\fP

\fBcloudnbd\fP [\fIoption\fP] \fBinfo\fP \
[\fIauth_option\fP] \
\fIbackend\fP \
\fIvolume\fP

\fBcloudnbd\fP [\fIoption\fP] \fBinit\fP \
[\fIauth_option\fP] \
[\fB\-b\fP \fIblock_size\fP] \
\fIbackend\fP \
\fIvolume\fP \
\fIsize\fP

\fBcloudnbd\fP [\fIoption\fP] \fBlist\fP \

\fBcloudnbd\fP [\fIoption\fP] \fBopen\fP \
[\fIauth_option\fP] \
[\fB\-s\fP \fIsize\fP] \
[\fB\-i\fP \fIip\fP] \
[\fB\-p\fP \fIport\fP] \
[\fB\-t\fP \fIcount\fP] \
[\fB\-r\fP \fIcount\fP] \
[\fB\-e\fP \fIsize\fP] \
[\fB\-\-foreground\fP] \
\fIbackend\fP \
\fIvolume\fP

\fBcloudnbd\fP [\fIoption\fP] \fBpasswd\fP \
[\fIauth_option\fP] \
\fIbackend\fP \
\fIvolume\fP

\fBcloudnbd\fP [\fIoption\fP] \fBresize\fP \
[\fIauth_option\fP] \
[\fB\-u\fP] \
\fIbackend\fP \
\fIvolume\fP \
\fIsize\fP

\fBcloudnbd\fP [\fIoption\fP] \fBstat\fP \
\fIbackend\fP \
\fIvolume\fP
.fi
.SH DESCRIPTION
\fBcloudnbd\fP provides access to cloud storage systems through Network
Block Device (NBD) driver of GNU/Linux kernel. NBD is a client-server
architecture and cloudnbd acts as the server. The client is provided by
NBD tools called \fInbd-client (1)\fP. The usual setup is to run
cloudnbd which connects to the cloud interface of the storage provider
and have nbd-client connect to it and bind the connection to an NBD
block device (e.g. /dev/nbd0). The block device then may be used just
like an ordinary one. One can format it with a file system, mount it and
read/write files from/to it.

Currently cloudnbd implements access to Google Storage for Developers
only. Amazon S3, while being more popular, lacks the read-after-write
consistency gaurantee and therefore is not yet implemented in cloudnbd.
All the \fIcommand\fPs that connect to the backend storage must be given
the name of the backend using \fIbackend\fP argument. See \fIBACKENDS\fP
section for more details.

\fIvolume\fP refers to the backend dependent path to the volume. See
\fIBACKENDS\fP section for more details.

All \fIsize\fP arguments follow the same format. Following variations
are supported:
.PP
.IP "1024"
means 1024 bytes
.IP "4K"
means 4000 bytes. Other letters that can be used are M, G, T, P. They
stand for Mega, Giga, Tera and Peta respectively.
.PP
.SH GENERAL OPTIONS
.PP
These \fIoption\fPs must be specified \fIbefore\fP the \fIcommand\fP name.
.PP
.IP "\fB\-h\fP, \fB\-\-help\fP"
Shows the list of all available commands as well as help for the
\fIGENERAL OPTIONS\fP.
.IP "\fB\-F\fP \fIpath\fP, \fB\-\-path\fP \fIpath\fP"
Specifies the path to custom config file. If this option is specified,
the default config files are ignored. See \fIFILES\fP section for
location of config files.
.PP
These options must be specified \fIafter\fP the \fIcommand\fP name.
.PP
.IP "\fB\-h\fP, \fB\-\-help\fP"
Shows the help for the specified command.
.SH AUTH OPTIONS
Following \fIauth_option\fPs apply to all \fIbackends\fP. See
\fIBACKENDS\fP section for details specific to each backend.
.PP
.IP "\fB-a\fP \fIkey\fP, \fB--access-key\fP \fIkey\fP"
Access key which depending on which backend is used, is analogous to the
user name of the storage provider.
.IP "\fB-k\fP \fIkey\fP, \fB--secret-key\fP \fIkey\fP"
Secret key which depending on which backend is used, is analogous to the
password for the storage provider.
.IP "\fB-y\fP \fIpassphrase\fP, \fB--passphrase\fP \fIpassphrase\fP"
Passphrase based on which \fBcloudnbd\fP encrypts the data before
sending it to the backend.
.PP
.SH CLOSE OPTIONS
Following \fIauth_option\fPs apply to all \fIbackends\fP. See
\fIBACKENDS\fP section for details specific to each backend.
.PP
.IP "\fB-a\fP \fIkey\fP, \fB--access-key\fP \fIkey\fP"
Access key which depending on which backend is used, is analogous to the
user name of the storage provider.
.IP "\fB-k\fP \fIkey\fP, \fB--secret-key\fP \fIkey\fP"
Secret key which depending on which backend is used, is analogous to the
password for the storage provider.
.IP "\fB-y\fP \fIpassphrase\fP, \fB--passphrase\fP \fIpassphrase\fP"
Passphrase based on which \fBcloudnbd\fP encrypts the data before
sending it to the backend.
.PP
.SH BACKENDS
.PP
.IP "Google Storage for Developers"
To use this backend, use \fBgs\fP as \fIbackend\fP for relevant
commands.
.SH FILES
.nf
/etc/cloudnbd.conf
~/.cloudnbd
.fi
.SH SEE ALSO
.nf
.I nbd-client (1)
https://github.com/oxplot/cloudnbd
.fi
.SH AUTHORS
.nf
See the AUTHORS file included with this program.
.SH BUGS
.nf
If you come across any bugs, please send a description of it to
mansour@oxplot.com
.fi
